// Placeholder Firebase options file.
// Replace this with the real file generated by:
//   flutterfire config
// and ensure Firebase billing is set up for Firebase AI (googleAI()).

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => throw UnsupportedError(
      'firebase_options.dart is not configured. Run `flutterfire config` to generate and replace this file.');
}
