name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  pdf_render: ^1.4.12
  http: ^1.2.2
  audioplayers: ^6.0.0
  file_picker: ^8.0.6
  web_socket_channel: ^2.4.0
  logger: ^2.0.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/example.pdf
    - assets/prompt.md
